### ISSUE TITLE
Add the "Input" and "Output" tags to containers

### ISSUE THREAD

**Issue by MasterOfBob777** [ChromaKey81/devsdream#21]
The "Input" and "Output" tags allow a container to interact with hoppers in a different way than default. The "Input" tag would require a slot and a direction (Ex: Input:{Slot:4b, Direction:"Left"}) this works similar to how furnaces accept items but you can define multiple slots. The "Output" tag needs any amount of slots (Ex: Output:{Slots:{4b}} Ex2: Output:{Slots:{4b,6b,8b}}) this works to similar to how furnaces output items.

**Comment by ChromaKey81** [comment]
We would do this through the JSON structure of complex blocks within objectpacks, not by adding new tags to preexisting vanilla blocks
